### PR TITLE
Fix access control

### PR DESCRIPTION
**Pull request by NewZeal**
Crucial permissions are missing, preventing access for non admin users to their messages.  The solution creates new permissions and applies them in the condition that manages access for edit, view and delete.

Oops accidentally included access handler which will be in another pull request.

### CODE REVIEW

**Comment by mccrodp** [comment]
It's all yours now @NewZeal, I'm not working with Drupal anymore. Great that the required fixes are coming in. Nice one! 😄

**Comment by mccrodp** [comment]
If you can get someone else from the community to help maintain, even better.

**Comment by mccrodp** [comment]
You have access to merge, right?

**Comment by NewZeal** [comment]
Can you describe again the process for deploying? I know you wrote it somewhere but it is lost in a thread.  If I merge into 8.x-1.x and push to this github repo, then the module is available here.  What do I do to have it deploy to the project page on drupal.org?

**Comment by NewZeal** [comment]
Merged into github repo.

**Comment by mccrodp** [comment]
Hey. It's just using git and managing a separate remote: https://git-scm.com/docs/git-remote

So, just having both remotes added (you already have origin as GH most likely), then add:

`git add remote drupal LINK` <- something like this

then

`git push 8.x.1.x drupal`

**Comment by NewZeal** [comment]
OK, got it.  First time using multiple remotes...

**Pull request merged**
